export const ASTEROID_API_KEY = 'BRPbNtxmPzs4j4EJvgLZPKLgfUCOXkmPEhrFouAQ';
export const ASTEROID_MIN_BIG_SIZE_METERS = 100;
export const MINIMUM_DISTANCE_IN_LUNAR_ORBITS_TO_RECOGNIZE_AN_ASTEROID_AS_DANGEROUS = 100;
